spring.datasource.url=jdbc:mysql://localhost/adopet_api?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER_MYSQL}
spring.datasource.password=${DB_PASSWORD_MYSQL}

# Não revela mais a Stack Trace em caso de erros
server.error.include-stacktrace=never